syntax = "proto3";

package project;

option go_package = "internal/delivery/grpc/pb;pb";

import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";
import "validate/validate.proto";

service ProjectService {
  rpc Create(CreateRequest) returns (CreateResponse);
  rpc GetProject(GetProjectRequest) returns (Project);
  rpc GetMyProjects(GetMyProjectsRequest) returns (GetMyProjectsResponse);
  rpc Update(UpdateRequest) returns (Project);
  rpc Delete(DeleteRequest) returns (google.protobuf.Empty);
  rpc AddToProject(AddToProjectRequest) returns (google.protobuf.Empty);
  rpc KickFromProject(KickFromProjectRequest) returns (google.protobuf.Empty);
  rpc GetMyRole(GetMyRoleRequest) returns (GetMyRoleResponse);
}

message CreateRequest {
  string name = 1 [(validate.rules).string = {min_len: 1, max_len: 100}];
}

message CreateResponse {
  string project_id = 1 [(validate.rules).string = {uuid: true}];
}

message GetProjectRequest {
  string project_id = 1 [(validate.rules).string = {uuid: true}];
}

message GetMyProjectsRequest {
  optional string query = 1;
}

message GetMyProjectsResponse {
  repeated Project projects = 1;
}

message UpdateRequest {
  string project_id = 1 [(validate.rules).string = {uuid: true}];
  string new_name = 2 [(validate.rules).string = {min_len: 1, max_len: 100}];
}

message DeleteRequest {
  string project_id = 1 [(validate.rules).string = {uuid: true}];
}

message Project {
  string id = 1 [(validate.rules).string = {uuid: true}];
  string name = 2;
  string owner_id = 3 [(validate.rules).string = {uuid: true}];
  google.protobuf.Timestamp created_at = 4;
  optional google.protobuf.Timestamp updated_at = 5;
}

message AddToProjectRequest {
  string user_id = 1 [(validate.rules).string = {uuid: true}];
  string project_id = 2 [(validate.rules).string = {uuid: true}];
}

message KickFromProjectRequest {
  string user_id = 1 [(validate.rules).string = {uuid: true}];
  string project_id = 2 [(validate.rules).string = {uuid: true}];
}

message GetMyRoleRequest {
  string project_id = 2 [(validate.rules).string = {uuid: true}];
}

message GetMyRoleResponse {
  Role role = 1;
}

enum Role {
  UNKNOWN = 0;
  OWNER = 1;
  MEMBER = 2;
}

message Empty {}

message ErrorDetail {
  string code = 1;
  map<string, string> errors = 2;
}